package PROG11.entornografico;

import static PROG11.conexiones.oracle.OracleConnextion.*;
import static PROG11.funcionalidad.Funcionalidad.parseRStoObject;
import PROG11.funcionalidad.FuncionalidadEntornoGrafico;
import static PROG11.funcionalidad.FuncionalidadEntornoGrafico.*;
import PROG11.funcionalidad.modelos.Player;
import PROG11.funcionalidad.modelos.Token;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ANTO
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form EntornoGrafico
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainTitleLabel = new javax.swing.JLabel();
        mainStartBtn = new javax.swing.JButton();
        mainRankBtn = new javax.swing.JButton();
        MainExitBtn = new javax.swing.JButton();
        mainAuthorLabel = new javax.swing.JLabel();
        mainVersionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(204, 204, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        mainPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        mainTitleLabel.setFont(new java.awt.Font("Consolas", 0, 60)); // NOI18N
        mainTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainTitleLabel.setText("TITULO DEL JUEGO");

        mainStartBtn.setText("mainStartBtn");
        mainStartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainStartBtnActionPerformed(evt);
            }
        });

        mainRankBtn.setText("mainRankBtn");
        mainRankBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainRankBtnActionPerformed(evt);
            }
        });

        MainExitBtn.setText("MainExitBtn");
        MainExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainExitBtnActionPerformed(evt);
            }
        });

        mainAuthorLabel.setText("mainAuthorLabel");

        mainVersionLabel.setText("v1.0.0");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(mainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(mainStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(mainRankBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(MainExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainAuthorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainVersionLabel)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(mainTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainStartBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mainRankBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainVersionLabel)
                    .addComponent(mainAuthorLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainStartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainStartBtnActionPerformed
        // Busco en la BBDD si hay un player con el nombre proporcionado
        try {
            String res = JOptionPane.showInputDialog(this, "Introduce tu nombre (Diferencia entre mayúsculas y minúsculas)");
            ResultSet rs = checkForPlayer(res);
            Player p = parseRStoObject(rs);

            if (p.getName() == null) {
                //Si no coincide el nombre, crea un nuevo player con ese nombre
                int resNewPlayer = JOptionPane.showConfirmDialog(this,
                        "No se ha encontrado un jugador con ese nombre. ¿Desea crear uno nuevo?",
                        "Crear nuevo jugador",
                        JOptionPane.YES_NO_OPTION);

                if (resNewPlayer == JOptionPane.YES_OPTION) {
                    Player player = new Player(res);
                    createPlayer(player);
                    Token.currentPlayer = player;
                    _openGameFrame();
                }
            } else {
                //Si hay un player con ese nombre, recupera el player
                Token.currentPlayer = parseRStoObject(rs);
                System.out.println("");
                _openGameFrame();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //_openGameFrame();
    }//GEN-LAST:event_mainStartBtnActionPerformed

    private void mainRankBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainRankBtnActionPerformed
        // TODO add your handling code here:
        _openRankFrame();
    }//GEN-LAST:event_mainRankBtnActionPerformed

    private void MainExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainExitBtnActionPerformed
        // TODO add your handling code here:
        closeApp();
    }//GEN-LAST:event_MainExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MainExitBtn;
    private javax.swing.JLabel mainAuthorLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainRankBtn;
    private javax.swing.JButton mainStartBtn;
    private javax.swing.JLabel mainTitleLabel;
    private javax.swing.JLabel mainVersionLabel;
    // End of variables declaration//GEN-END:variables

    //navegación entre frames
    private void _openGameFrame() {
        setVisible(false);
        openGameFrame();
    }

    private void _openRankFrame() {
        setVisible(false);
        openRankFrame();
    }
}
