--------------------------------------------------------
-- Archivo creado  - martes-mayo-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Type CUERPO_CELESTE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TYPE "HR"."CUERPO_CELESTE" AS OBJECT(
    nombre VARCHAR(20), codigo NUMBER, tipo VARCHAR(20), diametro NUMBER
);

/
--------------------------------------------------------
--  DDL for Table CUERPOS_CELESTES
--------------------------------------------------------

  CREATE TABLE "HR"."CUERPOS_CELESTES" OF "HR"."CUERPO_CELESTE" 
 OIDINDEX  ( PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ) 
 SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.CUERPOS_CELESTES
SET DEFINE OFF;
--------------------------------------------------------
--  Constraints for Table CUERPOS_CELESTES
--------------------------------------------------------

  ALTER TABLE "HR"."CUERPOS_CELESTES" ADD UNIQUE ("SYS_NC_OID$") RELY
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
