-- CONECTADO COMO EL USUARIO SYSTEM 

CREATE USER HR IDENTIFIED BY HR_mdyOnce31;

ALTER USER HR DEFAULT TABLESPACE USERS
              QUOTA UNLIMITED ON USERS;

ALTER USER HR TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO HR;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO HR;

-- LUEGO DE CREADO EL USUARIO HR, CREAR UNA CONEXION CON EL USUARIO

-- NOTA IMPORTANTE : se requieren permisos de SYSDBA para otorgar a HR 
