/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROG10.entornografico;

import static PROG10.funcionalidad.Funcionalidad.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ANTONIO SANZ PANS
 * TEMA 10 - PROGRAMACION
 */
public class EntornoGrafico extends javax.swing.JFrame {

    //static ArrayList<CuerpoCeleste> cuerposCelestes = new ArrayList<>();
    //static final String FILE_URL_SS = "./sistemasolar.dat";
//    static final String CC_TIPO_1 = "Planeta";
//    static final String CC_TIPO_2 = "Planeta enano";
//    static final String CC_TIPO_3 = "Luna";
//    static final String CUERPOS_CELESTES_NOT_FOUND = "No se han encontrado cuerpos celestes.";
    /**
     * Creates new form Index
     */
    public EntornoGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAdd = new javax.swing.JDialog();
        jLabelTitleAdd = new javax.swing.JLabel();
        jLabelCodeAdd = new javax.swing.JLabel();
        jLabelNameAdd = new javax.swing.JLabel();
        jLabelTypeAdd = new javax.swing.JLabel();
        jLabelDiameterAdd = new javax.swing.JLabel();
        jTextFieldCodeAdd = new javax.swing.JTextField();
        jTextFieldNameAdd = new javax.swing.JTextField();
        jComboBoxTypeAdd = new javax.swing.JComboBox<>();
        jTextFieldDiameterAdd = new javax.swing.JTextField();
        jButtonCancelAdd = new javax.swing.JButton();
        jButtonAceptAdd = new javax.swing.JButton();
        jLabelCodeError = new javax.swing.JLabel();
        jLabelDiameterError = new javax.swing.JLabel();
        jDialogShowAllData = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuerposCelestes = new javax.swing.JTable();
        jDialogSearchByCode = new javax.swing.JDialog();
        jTextFieldSearchCode = new javax.swing.JTextField();
        jLabelSearchType = new javax.swing.JLabel();
        jLabelSearchCodeTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSearchByCode = new javax.swing.JTable();
        jButtonSearchByCode = new javax.swing.JButton();
        jDialogSearchByType = new javax.swing.JDialog();
        jLabelSearchCode1 = new javax.swing.JLabel();
        jLabelSearchTypeTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSearchByType = new javax.swing.JTable();
        jButtonSearchByType = new javax.swing.JButton();
        jComboBoxSearchByType = new javax.swing.JComboBox<>();
        mainPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnSearchCode = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSearchType = new javax.swing.JButton();
        btnDeleteOne = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();

        jDialogAdd.setTitle("Añadir cuerpo celeste");
        jDialogAdd.setMinimumSize(null);
        jDialogAdd.setModal(true);
        jDialogAdd.setResizable(false);
        jDialogAdd.setSize(450,400);

        jLabelTitleAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitleAdd.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTitleAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleAdd.setText("Añadir nuevo cuerpo celeste");
        jLabelTitleAdd.setFocusable(false);
        jLabelTitleAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelCodeAdd.setText("Código");

        jLabelNameAdd.setText("Nombre");

        jLabelTypeAdd.setText("Tipo");

        jLabelDiameterAdd.setText("Diámetro");

        jTextFieldCodeAdd.setColumns(3);
        jTextFieldCodeAdd.setToolTipText("");
        jTextFieldCodeAdd.setMaximumSize(null);
        jTextFieldCodeAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodeAddKeyTyped(evt);
            }
        });

        jTextFieldNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameAddActionPerformed(evt);
            }
        });

        jComboBoxTypeAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planeta", "Planeta enano", "Luna" }));

        jTextFieldDiameterAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiameterAddActionPerformed(evt);
            }
        });
        jTextFieldDiameterAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiameterAddKeyTyped(evt);
            }
        });

        jButtonCancelAdd.setText("Cancelar");
        jButtonCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddActionPerformed(evt);
            }
        });

        jButtonAceptAdd.setText("Aceptar");
        jButtonAceptAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptAddActionPerformed(evt);
            }
        });

        jLabelCodeError.setText("El código deben ser 3 números");
        jLabelCodeError.setEnabled(false);
        jLabelCodeError.setFocusable(false);

        jLabelDiameterError.setText("El diámetro debe ser un úmero positivo de 6 o menos dígitos");
        jLabelDiameterError.setEnabled(false);
        jLabelDiameterError.setFocusable(false);

        javax.swing.GroupLayout jDialogAddLayout = new javax.swing.GroupLayout(jDialogAdd.getContentPane());
        jDialogAdd.getContentPane().setLayout(jDialogAddLayout);
        jDialogAddLayout.setHorizontalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddLayout.createSequentialGroup()
                        .addComponent(jButtonAceptAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonCancelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelTitleAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogAddLayout.createSequentialGroup()
                        .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNameAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTypeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDiameterAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDiameterError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameAdd)
                            .addComponent(jComboBoxTypeAdd, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDiameterAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCodeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCodeError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDialogAddLayout.setVerticalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleAdd)
                .addGap(18, 18, 18)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeAdd)
                    .addComponent(jTextFieldCodeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameAdd)
                    .addComponent(jTextFieldNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTypeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTypeAdd))
                .addGap(28, 28, 28)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiameterAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiameterAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDiameterError)
                .addGap(18, 18, 18)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptAdd)
                    .addComponent(jButtonCancelAdd))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jDialogShowAllData.setModal(true);
        jDialogShowAllData.setSize(450,400);

        jTableCuerposCelestes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCuerposCelestes);

        javax.swing.GroupLayout jDialogShowAllDataLayout = new javax.swing.GroupLayout(jDialogShowAllData.getContentPane());
        jDialogShowAllData.getContentPane().setLayout(jDialogShowAllDataLayout);
        jDialogShowAllDataLayout.setHorizontalGroup(
            jDialogShowAllDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialogShowAllDataLayout.setVerticalGroup(
            jDialogShowAllDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        jDialogSearchByCode.setModal(true);
        jDialogSearchByCode.setSize(450,400);

        jTextFieldSearchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchCodeActionPerformed(evt);
            }
        });
        jTextFieldSearchCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSearchCodeKeyTyped(evt);
            }
        });

        jLabelSearchType.setText("Código");

        jLabelSearchCodeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSearchCodeTitle.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSearchCodeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearchCodeTitle.setText("Buscador de cuerpos celestes por código");

        jTableSearchByCode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ));
        jTableSearchByCode.setEnabled(false);
        jTableSearchByCode.setFocusable(false);
        jScrollPane2.setViewportView(jTableSearchByCode);

        jButtonSearchByCode.setLabel("Buscar");
        jButtonSearchByCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogSearchByCodeLayout = new javax.swing.GroupLayout(jDialogSearchByCode.getContentPane());
        jDialogSearchByCode.getContentPane().setLayout(jDialogSearchByCodeLayout);
        jDialogSearchByCodeLayout.setHorizontalGroup(
            jDialogSearchByCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchByCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSearchByCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSearchByCodeLayout.createSequentialGroup()
                        .addComponent(jLabelSearchType)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSearchByCode))
                    .addComponent(jLabelSearchCodeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jDialogSearchByCodeLayout.setVerticalGroup(
            jDialogSearchByCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchByCodeLayout.createSequentialGroup()
                .addComponent(jLabelSearchCodeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSearchByCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchType)
                    .addComponent(jTextFieldSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearchByCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialogSearchByType.setModal(true);
        jDialogSearchByType.setSize(450,400);

        jLabelSearchCode1.setText("Tipo");

        jLabelSearchTypeTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSearchTypeTitle.setForeground(new java.awt.Color(0, 102, 255));
        jLabelSearchTypeTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSearchTypeTitle.setText("Buscador de cuerpos celestes por tipo");

        jTableSearchByType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ));
        jTableSearchByType.setEnabled(false);
        jTableSearchByType.setFocusable(false);
        jScrollPane3.setViewportView(jTableSearchByType);

        jButtonSearchByType.setLabel("Buscar");
        jButtonSearchByType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchByTypeActionPerformed(evt);
            }
        });

        jComboBoxSearchByType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planeta", "Planeta enano", "Luna" }));

        javax.swing.GroupLayout jDialogSearchByTypeLayout = new javax.swing.GroupLayout(jDialogSearchByType.getContentPane());
        jDialogSearchByType.getContentPane().setLayout(jDialogSearchByTypeLayout);
        jDialogSearchByTypeLayout.setHorizontalGroup(
            jDialogSearchByTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchByTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogSearchByTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogSearchByTypeLayout.createSequentialGroup()
                        .addComponent(jLabelSearchCode1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSearchByType, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearchByType))
                    .addComponent(jLabelSearchTypeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jDialogSearchByTypeLayout.setVerticalGroup(
            jDialogSearchByTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogSearchByTypeLayout.createSequentialGroup()
                .addComponent(jLabelSearchTypeTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogSearchByTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSearchCode1)
                    .addComponent(jButtonSearchByType)
                    .addComponent(jComboBoxSearchByType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRADOR DE CUERPOS CELESTES");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 183, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        mainPanel.setBackground(new java.awt.Color(68, 68, 68));
        mainPanel.setFocusable(false);

        btnAdd.setBackground(new java.awt.Color(89, 168, 105));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("AÑADIR");
        btnAdd.setBorderPainted(false);
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnShow.setBackground(new java.awt.Color(56, 159, 214));
        btnShow.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShow.setText("MOSTRAR");
        btnShow.setBorderPainted(false);
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnSearchCode.setBackground(new java.awt.Color(237, 162, 0));
        btnSearchCode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchCode.setText("<html><p align='center'>BUSCAR</p><p align='center'>POR</p><p align='center'>CODIGO</p></html>");
        btnSearchCode.setToolTipText("");
        btnSearchCode.setBorderPainted(false);
        btnSearchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeActionPerformed(evt);
            }
        });

        btnExit.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("SALIR");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSearchType.setBackground(new java.awt.Color(237, 162, 0));
        btnSearchType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSearchType.setText("<html><p align='center'>BUSCAR</p><p align='center'>POR</p><p align='center'>TIPO</p></html>");
        btnSearchType.setBorderPainted(false);
        btnSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTypeActionPerformed(evt);
            }
        });

        btnDeleteOne.setBackground(new java.awt.Color(219, 88, 96));
        btnDeleteOne.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteOne.setText("<html><p align='center'>BORRAR</p><p align='center'>POR</p><p align='center'>CODIGO</p></html>");
        btnDeleteOne.setBorderPainted(false);
        btnDeleteOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOneActionPerformed(evt);
            }
        });

        btnDeleteAll.setBackground(new java.awt.Color(219, 88, 96));
        btnDeleteAll.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteAll.setText("BORRAR TODO");
        btnDeleteAll.setBorderPainted(false);
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnDeleteOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EntornoGrafico().setVisible(true);
//            }
//        });
//    }

    private void btnDeleteOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOneActionPerformed
        System.out.println("Borrar por codigo");
        String res = JOptionPane.showInputDialog(rootPane, "Indica el código del cuerpo celeste que desea borrar");
        if (res != null) {
            Short code = Short.parseShort(res);
            deleteByCode(code);
        }

    }//GEN-LAST:event_btnDeleteOneActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println("Click boton añadir");
        jDialogAdd.setVisible(true);
        jDialogAdd.setSize(450, 400);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        System.out.println("Click boton mostrar lista");
        showAllCuerposCelestes();
        jDialogShowAllData.setVisible(true);
        jDialogShowAllData.setSize(450, 400);
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSearchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeActionPerformed
        System.out.println("Click buscar por codigo");
        jDialogSearchByCode.setVisible(true);
        jDialogSearchByCode.setSize(450, 400);
    }//GEN-LAST:event_btnSearchCodeActionPerformed

    private void btnSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTypeActionPerformed
        System.out.println("Click buscar por tipo");
        jDialogSearchByType.setVisible(true);
        jDialogSearchByType.setSize(450, 400);
    }//GEN-LAST:event_btnSearchTypeActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        System.out.println("Borrar todo");
        int res = JOptionPane.showConfirmDialog(
                rootPane,
                "¿Desea realmente borrar el archivo de datos?",
                "Borrado de datos",
                JOptionPane.YES_NO_OPTION);
        if (res == JOptionPane.YES_OPTION) {
            System.out.println("YES");
            deleteAll();
        } else {
            System.out.println("NO");
        }
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButtonAceptAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptAddActionPerformed
        setCuerpoCeleste();
        jDialogAdd.setVisible(false);
    }//GEN-LAST:event_jButtonAceptAddActionPerformed

    private void jButtonCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddActionPerformed
        closeAndResetJDialogAdd();
    }//GEN-LAST:event_jButtonCancelAddActionPerformed

    private void jTextFieldNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameAddActionPerformed
    }//GEN-LAST:event_jTextFieldNameAddActionPerformed

    private void jTextFieldSearchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchCodeActionPerformed
    }//GEN-LAST:event_jTextFieldSearchCodeActionPerformed

    private void jButtonSearchByCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByCodeActionPerformed
        searchCuerpoCelesteByCode();
    }//GEN-LAST:event_jButtonSearchByCodeActionPerformed

    private void jButtonSearchByTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchByTypeActionPerformed
        searchCuerpoCelesteByType();
    }//GEN-LAST:event_jButtonSearchByTypeActionPerformed

    private void jTextFieldCodeAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodeAddKeyTyped
        if (jTextFieldCodeAdd.getText().length() >= 3) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldCodeAddKeyTyped

    private void jTextFieldDiameterAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiameterAddActionPerformed
    }//GEN-LAST:event_jTextFieldDiameterAddActionPerformed

    private void jTextFieldDiameterAddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiameterAddKeyTyped
        if (jTextFieldDiameterAdd.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldDiameterAddKeyTyped

    private void jTextFieldSearchCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchCodeKeyTyped
        if (jTextFieldDiameterAdd.getText().length() >= 6) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSearchCodeKeyTyped

    private static void closeAndResetJDialogAdd() {
        jDialogAdd.setVisible(false);
        jTextFieldCodeAdd.setText("");
        jTextFieldNameAdd.setText("");
        jTextFieldDiameterAdd.setText("");
        jComboBoxTypeAdd.setSelectedIndex(0);
    }

    public static void errorMessage(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteOne;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchCode;
    private javax.swing.JButton btnSearchType;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton jButtonAceptAdd;
    private javax.swing.JButton jButtonCancelAdd;
    public static javax.swing.JButton jButtonSearchByCode;
    public static javax.swing.JButton jButtonSearchByType;
    public static javax.swing.JComboBox<String> jComboBoxSearchByType;
    public static javax.swing.JComboBox<String> jComboBoxTypeAdd;
    private static javax.swing.JDialog jDialogAdd;
    private javax.swing.JDialog jDialogSearchByCode;
    private javax.swing.JDialog jDialogSearchByType;
    private javax.swing.JDialog jDialogShowAllData;
    private javax.swing.JLabel jLabelCodeAdd;
    private javax.swing.JLabel jLabelCodeError;
    private javax.swing.JLabel jLabelDiameterAdd;
    private javax.swing.JLabel jLabelDiameterError;
    private javax.swing.JLabel jLabelNameAdd;
    private javax.swing.JLabel jLabelSearchCode1;
    private javax.swing.JLabel jLabelSearchCodeTitle;
    private javax.swing.JLabel jLabelSearchType;
    private javax.swing.JLabel jLabelSearchTypeTitle;
    private javax.swing.JLabel jLabelTitleAdd;
    private javax.swing.JLabel jLabelTypeAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JTable jTableCuerposCelestes;
    public static javax.swing.JTable jTableSearchByCode;
    public static javax.swing.JTable jTableSearchByType;
    public static javax.swing.JTextField jTextFieldCodeAdd;
    public static javax.swing.JTextField jTextFieldDiameterAdd;
    public static javax.swing.JTextField jTextFieldNameAdd;
    public static javax.swing.JTextField jTextFieldSearchCode;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
