/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EJERCICIO2.entornografico;

import static EJERCICIO2.funcionalidad.Func.*;

/**
 *
 * @author ANTO
 */
public class EntornoGrafico extends javax.swing.JFrame {

    //static ArrayList<CuerpoCeleste> cuerposCelestes = new ArrayList<>();
    //static final String FILE_URL_SS = "./sistemasolar.dat";
//    static final String CC_TIPO_1 = "Planeta";
//    static final String CC_TIPO_2 = "Planeta enano";
//    static final String CC_TIPO_3 = "Luna";
//    static final String CUERPOS_CELESTES_NOT_FOUND = "No se han encontrado cuerpos celestes.";
    /**
     * Creates new form Index
     */
    public EntornoGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAdd = new javax.swing.JDialog();
        jLabelTitleAdd = new javax.swing.JLabel();
        jLabelCodeAdd = new javax.swing.JLabel();
        jLabelNameAdd = new javax.swing.JLabel();
        jLabelTypeAdd = new javax.swing.JLabel();
        jLabelDiameterAdd = new javax.swing.JLabel();
        jTextFieldCodeAdd = new javax.swing.JTextField();
        jTextFieldNameAdd = new javax.swing.JTextField();
        jComboBoxTypeAdd = new javax.swing.JComboBox<>();
        jTextFieldDiameterAdd = new javax.swing.JTextField();
        jButtonCancelAdd = new javax.swing.JButton();
        jButtonAceptAdd = new javax.swing.JButton();
        jLabelCodeError = new javax.swing.JLabel();
        jLabelNameError = new javax.swing.JLabel();
        jLabelDiameterError = new javax.swing.JLabel();
        jLabelTypeError = new javax.swing.JLabel();
        jDialogShowAllData = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuerposCelestes = new javax.swing.JTable();
        mainPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        btnSearchCode = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSearchType = new javax.swing.JButton();
        btnDeleteOne = new javax.swing.JButton();
        btnDeleteAll = new javax.swing.JButton();

        jDialogAdd.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogAdd.setTitle("Añadir cuerpo celeste");
        jDialogAdd.setMinimumSize(null);
        jDialogAdd.setResizable(false);
        jDialogAdd.setSize(new java.awt.Dimension(425, 300));

        jLabelTitleAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTitleAdd.setForeground(new java.awt.Color(0, 102, 255));
        jLabelTitleAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitleAdd.setText("Añadir nuevo cuerpo celeste");
        jLabelTitleAdd.setFocusable(false);
        jLabelTitleAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelCodeAdd.setText("Código");

        jLabelNameAdd.setText("Nombre");

        jLabelTypeAdd.setText("Tipo");

        jLabelDiameterAdd.setText("Diámetro");

        jTextFieldCodeAdd.setColumns(3);
        jTextFieldCodeAdd.setToolTipText("");
        jTextFieldCodeAdd.setMaximumSize(null);

        jTextFieldNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameAddActionPerformed(evt);
            }
        });

        jComboBoxTypeAdd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Planeta", "Planeta enano", "Luna" }));

        jButtonCancelAdd.setText("Cancelar");
        jButtonCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddActionPerformed(evt);
            }
        });

        jButtonAceptAdd.setText("Aceptar");
        jButtonAceptAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptAddActionPerformed(evt);
            }
        });

        jLabelCodeError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelCodeError.setText("El formato del código es incorrecto (3 números)");
        jLabelCodeError.setFocusable(false);

        jLabelNameError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelNameError.setText("El formato es incorrecto");
        jLabelNameError.setFocusable(false);

        jLabelDiameterError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelDiameterError.setText("El formato del diámetro es incorrecto (Solo números)");
        jLabelDiameterError.setFocusable(false);

        jLabelTypeError.setForeground(new java.awt.Color(255, 0, 51));
        jLabelTypeError.setText("El formato es incorrecto");
        jLabelTypeError.setFocusable(false);

        javax.swing.GroupLayout jDialogAddLayout = new javax.swing.GroupLayout(jDialogAdd.getContentPane());
        jDialogAdd.getContentPane().setLayout(jDialogAddLayout);
        jDialogAddLayout.setHorizontalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogAddLayout.createSequentialGroup()
                        .addComponent(jButtonAceptAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)
                        .addComponent(jButtonCancelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelTitleAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialogAddLayout.createSequentialGroup()
                        .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCodeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNameAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTypeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDiameterAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDiameterError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                            .addComponent(jLabelTypeError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNameError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCodeError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNameAdd)
                            .addComponent(jComboBoxTypeAdd, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDiameterAdd, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCodeAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jDialogAddLayout.setVerticalGroup(
            jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogAddLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitleAdd)
                .addGap(18, 18, 18)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeAdd)
                    .addComponent(jTextFieldCodeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNameAdd)
                    .addComponent(jTextFieldNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNameError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTypeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTypeAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTypeError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDiameterAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDiameterAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDiameterError)
                .addGap(18, 18, 18)
                .addGroup(jDialogAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAceptAdd)
                    .addComponent(jButtonCancelAdd))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTableCuerposCelestes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Tipo", "Diámetro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCuerposCelestes);

        javax.swing.GroupLayout jDialogShowAllDataLayout = new javax.swing.GroupLayout(jDialogShowAllData.getContentPane());
        jDialogShowAllData.getContentPane().setLayout(jDialogShowAllDataLayout);
        jDialogShowAllDataLayout.setHorizontalGroup(
            jDialogShowAllDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jDialogShowAllDataLayout.setVerticalGroup(
            jDialogShowAllDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 183, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        mainPanel.setBackground(new java.awt.Color(68, 68, 68));
        mainPanel.setFocusable(false);

        btnAdd.setBackground(new java.awt.Color(89, 168, 105));
        btnAdd.setText("Añadir");
        btnAdd.setBorderPainted(false);
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnShow.setBackground(new java.awt.Color(56, 159, 214));
        btnShow.setText("mostrar");
        btnShow.setBorderPainted(false);
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnSearchCode.setBackground(new java.awt.Color(237, 162, 0));
        btnSearchCode.setText("Buscar pro codigo");
        btnSearchCode.setBorderPainted(false);
        btnSearchCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCodeActionPerformed(evt);
            }
        });

        btnExit.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.borderColor"));
        btnExit.setText("salir");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSearchType.setBackground(new java.awt.Color(237, 162, 0));
        btnSearchType.setText("Buscar por tipo");
        btnSearchType.setBorderPainted(false);
        btnSearchType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchTypeActionPerformed(evt);
            }
        });

        btnDeleteOne.setBackground(new java.awt.Color(219, 88, 96));
        btnDeleteOne.setText("borrar uno");
        btnDeleteOne.setBorderPainted(false);
        btnDeleteOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOneActionPerformed(evt);
            }
        });

        btnDeleteAll.setBackground(new java.awt.Color(219, 88, 96));
        btnDeleteAll.setText("borrar todo");
        btnDeleteAll.setBorderPainted(false);
        btnDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDeleteOne, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnDeleteAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(btnShow, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnSearchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnDeleteOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteAll, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EntornoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EntornoGrafico().setVisible(true);
//            }
//        });
//    }

    private void btnDeleteOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOneActionPerformed
        System.out.println("Borrar por codigo");
    }//GEN-LAST:event_btnDeleteOneActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        System.out.println("Click boton añadir");
        jDialogAdd.setVisible(true);
        jDialogAdd.setSize(450, 300);

        jLabelDiameterError.setVisible(false);
        jLabelNameError.setVisible(false);
        jLabelCodeError.setVisible(false);
        jLabelTypeError.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        System.out.println("Click boton mostrar lista");
        jDialogShowAllData.setVisible(true);
        jDialogShowAllData.setSize(600, 300);
        addDataTojTableCuerposCelestes();
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSearchCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCodeActionPerformed
        System.out.println("Click buscar por codigo");
    }//GEN-LAST:event_btnSearchCodeActionPerformed

    private void btnSearchTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchTypeActionPerformed
        System.out.println("Click buscar por tipo");
    }//GEN-LAST:event_btnSearchTypeActionPerformed

    private void btnDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllActionPerformed
        System.out.println("Borrar todo");
    }//GEN-LAST:event_btnDeleteAllActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exit();
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButtonAceptAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptAddActionPerformed
        setCuerpoCeleste();
    }//GEN-LAST:event_jButtonAceptAddActionPerformed

    private void jButtonCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddActionPerformed
        closeAndResetJDialogAdd();
    }//GEN-LAST:event_jButtonCancelAddActionPerformed

    private void jTextFieldNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameAddActionPerformed

private void createTableModelCuerposCelestes(){
    
}

//    private static void createCuerpoCeleste() {
//        try {
//            //Recoger datos del form
//            short code = Short.parseShort(jTextFieldCodeAdd.getText());
//            String name = jTextFieldNameAdd.getText();
//            int diameter = Integer.parseInt(jTextFieldDiameterAdd.getText());
//            String strType = jComboBoxTypeAdd.getSelectedItem().toString();
//            System.out.println("Datos recogidos");
//
//            //Crear cuerpo celeste
//            CuerpoCeleste miCuerpoCeleste = new CuerpoCeleste(code, name, strType, diameter);
//            cuerposCelestes.add(miCuerpoCeleste);
//            writeFileData(FILE_URL_SS, cuerposCelestes);
//
//        } catch (InputMismatchException e) {
//            //TODO: Añadir codigo para mostrar errores
////            System.out.println("ERROR: Formato incorrecto (" + e + ")");
////            runMenu();
//        } catch (Exception e) {
//            //TODO: Añadir codigo para mostrar errores
//
////            System.out.println("ERROR: " + e);
////            runMenu();
//            //throw new AssertionError(e);
//        }
//    }

    private static void closeAndResetJDialogAdd() {
        jDialogAdd.setVisible(false);
        jTextFieldCodeAdd.setText("");
        jTextFieldNameAdd.setText("");
        jTextFieldDiameterAdd.setText("");
        jComboBoxTypeAdd.setSelectedIndex(0);
    }

//    private static void resetFields(Container container) {
//        for (Component component : container.getComponents()) {
//            if (component instanceof JTextField jTextField) {
//                System.out.println(jTextField.getText());
//            }
//        }
//    }
//    private static void writeFileData(String urlFile, Object obj) {
//        try {
//            ObjectOutputStream writingFile = new ObjectOutputStream(new FileOutputStream(urlFile));
//            writingFile.writeObject(obj);
//            writingFile.close();
//            runMenu();
//
//        } catch (FileNotFoundException e) {
//            throw new AssertionError(e.getMessage());
//        } catch (Exception e) {
//            throw new AssertionError(e.getMessage());
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteAll;
    private javax.swing.JButton btnDeleteOne;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearchCode;
    private javax.swing.JButton btnSearchType;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton jButtonAceptAdd;
    private javax.swing.JButton jButtonCancelAdd;
    public static javax.swing.JComboBox<String> jComboBoxTypeAdd;
    private static javax.swing.JDialog jDialogAdd;
    private javax.swing.JDialog jDialogShowAllData;
    private javax.swing.JLabel jLabelCodeAdd;
    private javax.swing.JLabel jLabelCodeError;
    private javax.swing.JLabel jLabelDiameterAdd;
    private javax.swing.JLabel jLabelDiameterError;
    private javax.swing.JLabel jLabelNameAdd;
    private javax.swing.JLabel jLabelNameError;
    private javax.swing.JLabel jLabelTitleAdd;
    private javax.swing.JLabel jLabelTypeAdd;
    private javax.swing.JLabel jLabelTypeError;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableCuerposCelestes;
    public static javax.swing.JTextField jTextFieldCodeAdd;
    public static javax.swing.JTextField jTextFieldDiameterAdd;
    public static javax.swing.JTextField jTextFieldNameAdd;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
